defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.finetune.train_ibrl_agent.TrainIBRLAgent

name: ${env_name}_ibrl_mlp_ta${horizon_steps}
logdir: ${oc.env:DPPO_LOG_DIR}/gym-finetune/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
normalization_path: ${oc.env:DPPO_DATA_DIR}/gym/${env_name}/normalization.npz
base_policy_path: ${oc.env:DPPO_LOG_DIR}/gym-pretrain/hopper-medium-v2_pre_gaussian_mlp_ta1/2024-09-25_14-57-07_42/checkpoint/state_1000.pt
offline_dataset_path: ${oc.env:DPPO_DATA_DIR}/gym/${env_name}/train.npz

device: cuda:0
env_name: hopper-medium-v2
obs_dim: 11
action_dim: 3
cond_steps: 1
horizon_steps: 1
act_steps: 1

env:
  n_envs: 1
  name: ${env_name}
  max_episode_steps: 1000
  reset_at_iteration: False
  save_video: False
  best_reward_threshold_for_success: 3
  wrappers:
    mujoco_locomotion_lowdim:
      normalization_path: ${normalization_path}
    multi_step: 
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: True

wandb:
  entity: ${oc.env:DPPO_WANDB_ENTITY}
  project: ibrl-gym-${env_name}-finetune
  run: ${now:%H-%M-%S}_${name}

train:
  n_train_itr: 1000000
  n_critic_warmup_itr: 0
  n_steps: 1
  gamma: 0.99
  actor_lr: 1e-4
  actor_weight_decay: 0
  actor_lr_scheduler:
    first_cycle_steps: 1000
    warmup_steps: 10
    min_lr: 1e-4
  critic_lr: 1e-4
  critic_weight_decay: 0
  critic_lr_scheduler:
    first_cycle_steps: 1000
    warmup_steps: 10
    min_lr: 1e-4
  save_model_freq: 10000
  val_freq: 1000
  render:
    freq: 1
    num: 0
  log_freq: 200
  # IBRL specific
  batch_size: 256
  target_ema_rate: 0.005         
  scale_reward_factor: 0.1      
  critic_num_update: 1
  buffer_size: 1000000
  n_val_steps: 10000
  n_explore_steps: 0 
  update_freq: 2

model:
  _target_: model.rl.gaussian_ibrl.IBRL_Gaussian
  network_path: ${base_policy_path}
  randn_clip_value: 3
  n_critics: 2            # Ensemble size for critic models
  actor_explore_std: 0.1
  critic_clip_c: 0.3
  soft_action_sample: False
  soft_action_sample_beta: 0.1
  actor:
    _target_: model.common.mlp_gaussian.Gaussian_MLP
    mlp_dims: [256, 256]
    activation_type: ReLU
    residual_style: False
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    horizon_steps: ${horizon_steps}
    transition_dim: ${action_dim}
    std_max: ${model.actor_explore_std}
    std_min: ${model.actor_explore_std}
    # fixed_std: ${actor_explore_std}
    use_dropout: True
    dropout_rate: 0.5
    # learn_fixed_std: True
  critic:
    _target_: model.common.critic.CriticObsAct
    mlp_dims: [256, 256]
    activation_type: ReLU
    residual_style: False
    use_layernorm: True
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    action_dim: ${action_dim}
    action_steps: ${act_steps}
  horizon_steps: ${horizon_steps}
  device: ${device}

offline_dataset:
  _target_: agent.dataset.sequence.StitchedTransitionDataset
  dataset_path: ${offline_dataset_path}
  horizon_steps: ${horizon_steps}
  cond_steps: ${cond_steps}
  device: ${device}