defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.pretrain.train_gaussian_agent.TrainGaussianAgent

name: ${env}_pre_gaussian_mlp_ta${horizon_steps}
logdir: ${oc.env:DPPO_LOG_DIR}/gym-pretrain/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
train_dataset_path: ${oc.env:DPPO_DATA_DIR}/gym/${env}/train.npz

seed: 42
device: cuda:0
env: hopper-medium-v2
obs_dim: 11
action_dim: 3
transition_dim: ${action_dim}
horizon_steps: 1
cond_steps: 1

wandb:
  entity: ${oc.env:DPPO_WANDB_ENTITY}
  project: gym-${env}-pretrain-gaussian
  run: ${now:%H-%M-%S}_${name}

train:
  n_epochs: 10000
  batch_size: 128
  learning_rate: 1e-3
  weight_decay: 1e-6
  lr_scheduler:
    first_cycle_steps: 3000
    warmup_steps: 1
    min_lr: 1e-4
  epoch_start_ema: 10
  update_ema_freq: 5
  save_model_freq: 500

model:
  _target_: model.common.gaussian.GaussianModel
  network:
    _target_: model.common.mlp_gaussian.Gaussian_MLP
    mlp_dims: [512, 512, 512]
    activation_type: ReLU
    residual_style: False
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    horizon_steps: ${horizon_steps}
    transition_dim: ${transition_dim}
  horizon_steps: ${horizon_steps}
  device: ${device}

ema:
  decay: 0.995

train_dataset:
  _target_: agent.dataset.sequence.StitchedSequenceDataset
  dataset_path: ${train_dataset_path}
  horizon_steps: ${horizon_steps}
  cond_steps: ${cond_steps}
  device: ${device}